### ISSUE TITLE
How to install this package?

### ISSUE THREAD

**Issue by findmyway** [ETH-DISCO/rlp#1]
The link in the https://github.com/ETH-DISCO/rlp?tab=readme-ov-file#step-by-step-guide seems to be broken.

fatal: repository 'https://github.com/a8142stm/qw8q.git/' not found

Also, when executing `install.sh`

```
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Checking for module 'gtk+-2.0'
--   No package 'gtk+-2.0' found
CMake Error at cmake/platforms/unix.cmake:36 (message):
  Unable to find any usable version of GTK.
Call Stack (most recent call first):
  cmake/setup.cmake:37 (include)
  CMakeLists.txt:6 (include)
```

**Comment by besterma** [comment]
Hi @findmyway, I've updated the README to include the correct link. For your error, I recommend that you install either gtk 3 or gtk 2. Let me know if this helps.

**Comment by findmyway** [comment]
Just tried again:

`make: *** No rule to make target 'icons'.  Stop.`

**Comment by findmyway** [comment]
Also, `pip install -e .` should be executed before activating the virtual env. Otherwise, it is installed to the default env.

**Comment by besterma** [comment]
`pip install -e .` has to be executed **after** activating the virtual env so that it is installed in the virtual env (how it is done in `install.sh`).

Are you sure that you are executing the original `install.sh`?
Please ensure that you run `cmake ../../puzzles`  before `make icons` so that the build files are actually present.

I have just reproduced the installation from scratch using `install.sh` and could unfortunately not reproduce your error.

**Comment by findmyway** [comment]
Could you also provide a docker file?

I'm really interested in working on a Julia wrapper for this package. Unfortunately stuck on the very first step...
